name: "Matrix CI Bot"
description: "Sync workflow status to Matrix"
inputs:
  room-id: # id of input
    description: "Which room to send to"
    required: true
  username:
    description: "Matrix bot account username"
    required: true
  password:
    description: "Matrix bot account password"
    required: true
  homeserver-url:
    description: "The Homeserver url"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/onichandame/matrix-ci-bot:dev"
  env:
    HOME_SERVER: "${{ inputs.homeserver-url }}"
    ROOM_ID: "${{ inputs.room-id }}"
    USERNAME: "${{ inputs.username }}"
    PASSWORD: "${{ inputs.password }}"
